# Generated by Django 3.2.4 on 2021-06-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210626_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Anonymous', max_length=40),
        ),
    ]
