# Generated by Django 3.2.4 on 2021-10-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_alter_address_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25, null=True, unique=True)),
                ('order_amount', models.DecimalField(decimal_places=2, default=None, max_digits=50, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.TextField(max_length=150)),
                ('billing_address', models.TextField(max_length=150)),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=12)),
                ('transaction_id', models.CharField(max_length=50, null=True)),
                ('payment_id', models.CharField(max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('Credit Card/Debit Card', 'Credit Card/Debit Card'), ('COD', 'COD'), ('Wallet', 'Wallet'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], max_length=30, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('electronics', 'Electronics'), ('Other', 'Other'), ("men's clothing", "men's clothing"), ("women's clothing", "women's clothing"), ('jewelery', 'jewelery')], default=None, max_length=30, null=True)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_unitprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(default='products/default.jpg', upload_to='products')),
                ('stock', models.PositiveIntegerField()),
                ('sku', models.CharField(blank=True, default='SKU7DN5WECY7I', max_length=20)),
                ('dimensions', models.CharField(blank=True, help_text='e.g - LxBxH', max_length=15)),
                ('weight', models.FloatField(blank=True, help_text='in Kg.', null=True)),
                ('sku_barcode', models.ImageField(blank=True, upload_to='products/barcodes')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=120)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('helpful_count', models.PositiveIntegerField(default=0, null=True)),
                ('report_count', models.PositiveIntegerField(default=0, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomm.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomm.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecomm.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecomm.product')),
            ],
        ),
    ]
