# Generated by Django 3.2.4 on 2021-10-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
