# Generated by Django 3.2.4 on 2021-06-28 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomm', '0006_auto_20210628_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.UUIDField(default='ef92d0e867bf4e119423c10d205aa604', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
