# Generated by Django 3.2.4 on 2021-06-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0007_auto_20210628_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.UUIDField(default='05359aa707f041a292752f2c3a19a28d', unique=True),
        ),
    ]
