# Generated by Django 3.2.4 on 2021-06-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_profile_name'),
        ('ecomm', '0009_auto_20210629_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='2ca80353705c4672a423723fc4f0a18f', unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
