# Generated by Django 3.2.4 on 2021-06-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0011_auto_20210630_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='36ccbe98e42e410a9680cdaaf1b7a6b7', unique=True),
        ),
    ]
