# Generated by Django 3.2.4 on 2021-07-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0012_auto_20210630_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='5b23370405cc4fb4a701f19885be3361', unique=True),
        ),
    ]
