# Generated by Django 3.2.4 on 2021-07-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0013_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='84edc4f146764e22a5e2f97123680331', unique=True),
        ),
    ]
