# Generated by Django 3.2.4 on 2021-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0014_auto_20210701_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='87cfc20093e0428fba68c43c6af94457', unique=True),
        ),
    ]
