# Generated by Django 3.2.4 on 2021-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0015_auto_20210701_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='af1ae0f17e474f66913ee3a4a5e65a81', unique=True),
        ),
    ]
