# Generated by Django 3.2.4 on 2021-07-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0018_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='d9673f7c6c6a47e28dbdcc0e31cb3c71', primary_key=True, serialize=False, unique=True),
        ),
    ]
