# Generated by Django 3.2.4 on 2021-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0019_auto_20210703_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card/Debit Card', 'Credit Card/Debit Card'), ('COD', 'COD'), ('Wallet', 'Wallet'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='a772a47631654a0f94cd23557e04b8cc', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=150),
        ),
    ]
