# Generated by Django 3.2.4 on 2021-07-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0020_auto_20210704_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discount_unitprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unitprice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='baa289e86182442890736886a2eea93e', primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.product')),
            ],
        ),
    ]
