# Generated by Django 3.2.4 on 2021-07-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0021_auto_20210705_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='79ad194307774e7f8546bda7b1ada045', primary_key=True, serialize=False, unique=True),
        ),
    ]
