# Generated by Django 3.2.4 on 2021-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0022_auto_20210705_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='783a6db473f5484e8ae02f4424efded4', primary_key=True, serialize=False, unique=True),
        ),
    ]
