# Generated by Django 3.2.4 on 2021-07-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0023_auto_20210705_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='e1b7db1551804c76ab30d4cb8d31407c', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Ordered', max_length=12),
        ),
    ]
