# Generated by Django 3.2.4 on 2021-09-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0025_auto_20210707_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g - LxBxH', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, help_text='in Kg.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default='cc769e05b6a644f8813be4996306232c', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('electronics', 'Electronics'), ('Other', 'Other'), ("men's clothing", "men's clothing"), ("women's clothing", "women's clothing"), ('jewelery', 'jewelery')], default=None, max_length=30, null=True),
        ),
    ]
