# Generated by Django 3.2.4 on 2021-09-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0028_product_sku_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku_barcode',
            new_name='barcode',
        ),
    ]
