# Generated by Django 3.2.4 on 2021-09-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0029_rename_sku_barcode_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.AddField(
            model_name='product',
            name='sku_barcode',
            field=models.ImageField(blank=True, upload_to='products/barcodes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='SKUVCGNZAIUJZ', max_length=20),
        ),
    ]
