# Generated by Django 3.2.4 on 2021-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0030_auto_20210929_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ODR-2FHCHOKNWN53WDM50BC3', max_length=25, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='SKUUN5DJ9YAZ3', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, help_text='in Kg.', null=True),
        ),
    ]
