# Generated by Django 3.2.4 on 2021-10-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0035_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='SKUCN9MZC7VT2', max_length=20),
        ),
    ]
