# Generated by Django 3.2.4 on 2021-10-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0036_auto_20211004_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='SKU2PTZXS796M', max_length=20),
        ),
    ]
