# Generated by Django 3.2.4 on 2021-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellercentral', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='offering_price',
            field=models.DecimalField(decimal_places=2, help_text='put what price you wanna offer for this product', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='display_name',
            field=models.CharField(blank=True, help_text='It will be fetch automatically from user profile', max_length=40, null=True),
        ),
    ]
